
driver:
  name: dokken
  chef_version: latest
  privileged: ture

transport:
  name: dokken

provisioner:
  name: dokken

platforms:
  - name: centos73
    driver:
      image: centos:7.3.1611
      pid_one_command: /usr/lib/systemd/systemd
      intermediate_instructions:
        - RUN yum install -y lsof which systemd-sysv initscript net-tools iproute

verifier:
  name: inspec

suites:
  - name: default
    run_list:
      - recipe[nginx::default]
    verifier:
      inspec_test:
        - test/smoke/default/
    attributes:
